Repository canonical/postgresql-k8s-operator, pull requests merged in 2025-03, with the labels that each got.

#876 [MISC] Sanitize PostgreSQL extra-user-roles arg
  lib/charms/postgresql_k8s/v0/postgresql.py
  src/charm.py
  src/relations/postgresql_provider.py
  tests/unit/test_postgresql_provider.py
Labels: Libraries: Out of sync, not bug or enhancement

#879 [MISC] Fix PostgreSQL lib function signature
  lib/charms/postgresql_k8s/v0/postgresql.py
Labels: Libraries: Out of sync, not bug or enhancement

#884 [MISC] Skip backup tests without creds
  lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py
  tests/integration/conftest.py
  tests/integration/test_backups_aws.py
  tests/integration/test_backups_gcp.py
  tests/integration/test_backups_pitr_aws.py
  tests/integration/test_backups_pitr_gcp.py
Labels: Libraries: OK, not bug or enhancement

#867 [DPE-6679] PostgreSQL Config Improvement
  config.yaml
  lib/charms/postgresql_k8s/v0/postgresql.py
  src/charm.py
  src/config.py
  tests/integration/test_config.py
Labels: enhancement

#892 [DPE-6675] Add wal_keep_size config option
  config.yaml
  src/charm.py
  src/config.py
Labels: enhancement, Libraries: Out of sync

#881 [DPE-6344] LDAP I: Create access groups
  lib/charms/postgresql_k8s/v0/postgresql.py
  src/charm.py
  src/relations/db.py
  src/relations/postgresql_provider.py
  src/upgrade.py
  tests/unit/test_db.py
  tests/unit/test_postgresql.py
  tests/unit/test_postgresql_provider.py
Labels: enhancement, Libraries: Out of sync

#883 [DPE-6344] LDAP II: Include charm libs
  lib/charms/certificate_transfer_interface/v0/certificate_transfer.py
  lib/charms/glauth_k8s/v0/ldap.py
  lib/charms/postgresql_k8s/v0/postgresql_tls.py
  metadata.yaml
  pyproject.toml
  src/charm.py
  tests/integration/helpers.py
  tests/integration/test_backups_pitr_aws.py
  tests/integration/test_backups_pitr_gcp.py
  tests/integration/test_tls.py
  tests/unit/test_charm.py
  tests/unit/test_postgresql_tls.py
Labels: enhancement, Libraries: Out of sync

#894 [DPE-6112] Dual branch config and test tweaks
  .github/renovate.json5
  .github/workflows/check_pr.yaml
  tests/integration/ha_tests/test_smoke.py
  tests/integration/ha_tests/test_upgrade_from_stable.py
  tests/integration/new_relations/test_new_relations_1.py
  tests/integration/test_backups_aws.py
  tests/integration/test_backups_gcp.py
  tests/integration/test_backups_pitr_aws.py
  tests/integration/test_backups_pitr_gcp.py
  tests/integration/test_plugins.py
  tests/integration/test_tls.py
  tests/spread/test_smoke.py/task.yaml
  tests/spread/test_upgrade_from_stable.py/task.yaml
Labels: Libraries: Out of sync, not bug or enhancement

#875 [DPE-6555] Add read only URIs
  lib/charms/certificate_transfer_interface/v0/certificate_transfer.py
  lib/charms/data_platform_libs/v0/data_interfaces.py
  lib/charms/glauth_k8s/v0/ldap.py
  lib/charms/loki_k8s/v1/loki_push_api.py
  lib/charms/tempo_coordinator_k8s/v0/tracing.py
  src/relations/postgresql_provider.py
  tests/integration/new_relations/helpers.py
  tests/integration/new_relations/test_new_relations_1.py
  tests/integration/test_backups_aws.py
  tests/integration/test_backups_gcp.py
  tests/integration/test_backups_pitr_aws.py
  tests/integration/test_backups_pitr_gcp.py
  tests/integration/test_tls.py
Labels: enhancement, Libraries: OK

#886 [DPE-6344] LDAP III: Define config and handlers
  config.yaml
  src/charm.py
  src/config.py
  src/ldap.py
  src/patroni.py
  templates/patroni.yml.j2
  tests/integration/test_ldap.py
  tests/spread/test_ldap/task.yaml
  tests/unit/test_charm.py
  tests/unit/test_ldap.py
  tests/unit/test_patroni.py
Labels: enhancement, Libraries: OK

#898 [DPE-6112] Sync main 16
  config.yaml
  lib/charms/certificate_transfer_interface/v0/certificate_transfer.py
  lib/charms/data_platform_libs/v0/data_interfaces.py
  lib/charms/glauth_k8s/v0/ldap.py
  lib/charms/loki_k8s/v1/loki_push_api.py
  lib/charms/postgresql_k8s/v0/postgresql.py
  lib/charms/postgresql_k8s/v0/postgresql_tls.py
  lib/charms/tempo_coordinator_k8s/v0/tracing.py
  metadata.yaml
  pyproject.toml
  src/charm.py
  src/config.py
  src/ldap.py
  src/patroni.py
  src/relations/postgresql_provider.py
  src/upgrade.py
  templates/patroni.yml.j2
  tests/integration/helpers.py
  tests/integration/new_relations/helpers.py
  tests/integration/new_relations/test_new_relations_1.py
  tests/integration/test_backups_pitr_aws.py
  tests/integration/test_backups_pitr_gcp.py
  tests/integration/test_ldap.py
  tests/integration/test_tls.py
  tests/spread/test_ldap/task.yaml
  tests/unit/test_charm.py
  tests/unit/test_ldap.py
  tests/unit/test_patroni.py
  tests/unit/test_postgresql.py
  tests/unit/test_postgresql_provider.py
  tests/unit/test_postgresql_tls.py
Labels: Libraries: OK, not bug or enhancement

#897 [DPE-6344] LDAP IV: Define pebble service
  src/backups.py
  src/charm.py
  src/relations/async_replication.py
  tests/unit/test_charm.py
Labels: enhancement, Libraries: OK

#900 [DPE-6344] LDAP V: Define mapping option
  config.yaml
  lib/charms/postgresql_k8s/v0/postgresql.py
  src/charm.py
  src/config.py
  tests/unit/test_charm.py
  tests/unit/test_postgresql.py
Labels: enhancement, Libraries: Out of sync
