Repository canonical/postgresql-k8s-operator, pull requests merged in 2025-07, with the labels that each got.

#1020 [DPE-7549] Add compression and restore max-process
  src/backups.py
  templates/pgbackrest.conf.j2
  tests/unit/test_backups.py
Labels: enhancement, Libraries: Out of sync

#1030 Remove markdown-linter action (16)
  .github/workflows/markdown-style-checks.yml
  docs/.sphinx/.markdownlint.json
Labels: documentation, not bug or enhancement

#1028 Remove markdown-linter action
  .github/workflows/markdown-style-checks.yml
  docs/.sphinx/.markdownlint.json
Labels: documentation, Libraries: Out of sync, not bug or enhancement

#1033 [MISC] Fix data integrator tests
  tests/integration/new_relations/test_new_relations_1.py
  tests/integration/new_relations/test_relations_coherence.py
Labels: Libraries: Out of sync, not bug or enhancement

#1031 Bump PG slots max_replication_slots / max_wal_senders = 25
  src/charm.py
Labels: enhancement, Libraries: Out of sync

#1034 [DPE-7594] Remove the trigger and observe changes in pg_database
  lib/charms/postgresql_k8s/v0/postgresql.py
  scripts/authorisation_rules_observer.py
  src/authorisation_rules_observer.py
  src/charm.py
  tests/integration/test_pg_hba.py
  tests/unit/test_authorisation_rules_observer.py
Labels: Libraries: Out of sync

#1007 [DPE-7594] Sync up pg_hba changes and remove trigger
  lib/charms/postgresql_k8s/v0/postgresql.py
  scripts/authorisation_rules_observer.py
  src/authorisation_rules_observer.py
  src/charm.py
  src/relations/postgresql_provider.py
  tests/integration/ha_tests/helpers.py
  tests/integration/ha_tests/test_async_replication.py
  tests/integration/ha_tests/test_replication.py
  tests/integration/ha_tests/test_self_healing_1.py
  tests/integration/ha_tests/test_self_healing_2.py
  tests/integration/ha_tests/test_upgrade.py
  tests/integration/ha_tests/test_upgrade_from_stable.py
  tests/integration/new_relations/test_new_relations_1.py
  tests/integration/new_relations/test_relations_coherence.py
  tests/integration/relations/test_relations.py
  tests/integration/test_db.py
  tests/integration/test_pg_hba.py
  tests/unit/test_authorisation_rules_observer.py
  tests/unit/test_charm.py
Labels: Libraries: Out of sync, not bug or enhancement

#1038 [MISC] Sync 14 to 16
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/approve_renovate_pr.yaml
  .github/workflows/check_pr.yaml
  .github/workflows/ci.yaml
  .github/workflows/cla-check.yml
  .github/workflows/lib-check.yaml
  .github/workflows/promote.yaml
  .github/workflows/release.yaml
  .gitignore
  CONTRIBUTING.md
  SECURITY.md
  lib/charms/data_platform_libs/v0/data_interfaces.py
  lib/charms/data_platform_libs/v0/upgrade.py
  lib/charms/postgresql_k8s/v0/postgresql.py
  scripts/authorisation_rules_observer.py
  src/authorisation_rules_observer.py
  src/charm.py
  src/relations/postgresql_provider.py
  tests/integration/ha_tests/helpers.py
  tests/integration/ha_tests/test_async_replication.py
  tests/integration/ha_tests/test_replication.py
  tests/integration/ha_tests/test_self_healing_1.py
  tests/integration/ha_tests/test_self_healing_2.py
  tests/integration/ha_tests/test_upgrade.py
  tests/integration/ha_tests/test_upgrade_from_stable.py
  tests/integration/new_relations/test_new_relations_1.py
  tests/integration/test_pg_hba.py
  tests/unit/conftest.py
  tests/unit/test_authorisation_rules_observer.py
  tests/unit/test_charm.py
Labels: Libraries: Out of sync, not bug or enhancement
