Repository canonical/postgresql-k8s-operator, pull requests merged in 2025-08, with the labels that each got.

#1042 [DPE-7870] Reorder map logic
  src/charm.py
Labels: Libraries: Out of sync, not bug or enhancement

#1051 [DPE-5311] Patch failsafe mode on upgrade
  src/patroni.py
  src/upgrade.py
  tests/integration/ha_tests/helpers.py
  tests/integration/ha_tests/test_upgrade_from_stable.py
  tests/integration/new_relations/test_new_relations_2.py
  tests/unit/test_patroni.py
Labels: bug, Libraries: Out of sync

#1041 [DPE-7594] Add custom users to pg_hba filter
  .github/workflows/cla-check.yml
  lib/charms/postgresql_k8s/v0/postgresql.py
  src/charm.py
Labels: Libraries: Out of sync, not bug or enhancement

#1066 [MISC] Disable discourse test and remove old CLA check
  .github/workflows/cla-check.yml
  tests/integration/new_relations/test_new_relations_2.py
Labels: Libraries: Out of sync, not bug or enhancement

#1068 DPE-6901 Replace md5 with scram-sha-256 in patroni/pg_hba.conf
  src/patroni.py
  templates/patroni.yml.j2
  tests/integration/test_config.py
  tests/unit/test_patroni.py
Labels: bug, Libraries: Out of sync

#1060 [DPE-7379] custom entity name
  lib/charms/data_platform_libs/v0/data_interfaces.py
  src/charm.py
  src/constants.py
  src/relations/postgresql_provider.py
Labels: enhancement, Libraries: Out of sync
