Repository canonical/postgresql-k8s-operator, pull requests merged in 2025-06, with the labels that each got.

#994 Add redirects for all charmhub pages (14)
  docs/conf.py
  docs/explanation/index.md
  docs/explanation/interfaces-and-endpoints.md
  docs/explanation/users.md
  docs/how-to/development/integrate-with-your-charm.md
  docs/index.md
  docs/redirects.txt
  docs/requirements.txt
Labels: documentation, not bug or enhancement

#997 DPE-6662 Fix pgbackrest logs names on logs rotation
  templates/pgbackrest.logrotate.j2
Labels: bug, Libraries: Out of sync

#1000 [MISC] Renovate team
  .github/renovate.json5
Labels: Libraries: Out of sync, not bug or enhancement

#999 [MISC] Renovate team
  .github/renovate.json5
Labels: Libraries: Out of sync, not bug or enhancement

#1001 [MISC] Hold database created hook for pg_hba changes
  lib/charms/postgresql_k8s/v0/postgresql.py
  src/relations/postgresql_provider.py
  tests/unit/test_postgresql_provider.py
Labels: Libraries: Out of sync, not bug or enhancement

#1006 fix: internal reference typo
  docs/explanation/legacy-charm.md
Labels: documentation, not bug or enhancement

#996 DPE-6662 Fix pgbackrest logs names on logs rotation
  templates/pgbackrest.logrotate.j2
Labels: bug, Libraries: Out of sync

#1014 [MISC] Update libs and remove warning
  .github/workflows/cla-check.yml
  .github/workflows/lib-check.yaml
  lib/charms/data_platform_libs/v0/data_interfaces.py
  lib/charms/data_platform_libs/v0/upgrade.py
  lib/charms/grafana_k8s/v0/grafana_dashboard.py
  lib/charms/loki_k8s/v1/loki_push_api.py
  lib/charms/prometheus_k8s/v0/prometheus_scrape.py
  lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py
  lib/charms/tempo_coordinator_k8s/v0/tracing.py
  lib/charms/tls_certificates_interface/v2/tls_certificates.py
  src/charm.py
  tests/unit/conftest.py
  tests/unit/test_charm.py
Labels: enhancement, Libraries: OK

#1016 Fix automatic doc checks
  docs/.custom_wordlist.txt
  docs/.sphinx/spellingcheck.yaml
  docs/conf.py
  docs/explanation/architecture.md
  docs/explanation/flowcharts/backups.md
  docs/explanation/interfaces-and-endpoints.md
  docs/explanation/juju.md
  docs/explanation/legacy-charm.md
  docs/explanation/logs.md
  docs/explanation/security/cryptography.md
  docs/explanation/security/index.md
  docs/explanation/users.md
  docs/how-to/back-up-and-restore/configure-s3-radosgw.md
  docs/how-to/back-up-and-restore/manage-backup-retention.md
  docs/how-to/cross-regional-async-replication/index.md
  docs/how-to/cross-regional-async-replication/integrate-with-a-client-app.md
  docs/how-to/cross-regional-async-replication/remove-or-recover-a-cluster.md
  docs/how-to/cross-regional-async-replication/set-up-clusters.md
  docs/how-to/deploy/air-gapped.md
  docs/how-to/deploy/aks.md
  docs/how-to/deploy/canonical-k8s.md
  docs/how-to/deploy/gke.md
  docs/how-to/deploy/index.md
  docs/how-to/deploy/multi-az.md
  docs/how-to/deploy/terraform.md
  docs/how-to/development/integrate-with-your-charm.md
  docs/how-to/development/migrate-data-via-pg-dump.md
  docs/how-to/enable-ldap.md
  docs/how-to/enable-plugins-extensions.md
  docs/how-to/monitoring-cos/enable-alert-rules.md
  docs/how-to/monitoring-cos/enable-monitoring.md
  docs/how-to/monitoring-cos/enable-tracing.md
  docs/how-to/scale-replicas.md
  docs/index.md
  docs/reference/alert-rules.md
  docs/reference/contacts.md
  docs/reference/performance-and-resources.md
  docs/reference/releases.md
  docs/reference/statuses.md
  docs/reference/system-requirements.md
  docs/tutorial/index.md
Labels: documentation, not bug or enhancement
