Repository canonical/postgresql-k8s-operator, pull requests merged in 2025-04, with the labels that each got.

#911 [MISC] Sync main to 16/edge
  config.yaml
  lib/charms/postgresql_k8s/v0/postgresql.py
  src/backups.py
  src/charm.py
  src/config.py
  src/relations/async_replication.py
  tests/unit/test_charm.py
  tests/unit/test_postgresql.py
Labels: Libraries: OK, not bug or enhancement

#901 [MISC] Conditional checksum calculation
  poetry.lock
  pyproject.toml
  src/backups.py
  tests/integration/test_backups_gcp.py
  tests/unit/test_backups.py
Labels: Libraries: OK, not bug or enhancement

#914 Create SECURITY.md
  SECURITY.md
Labels: not bug or enhancement

#920 [MISC] Add missing connection vars
  lib/charms/postgresql_k8s/v0/postgresql.py
Labels: bug, Libraries: Out of sync

#915 [DPE-6218] Static code analysis
  .github/workflows/tiobe_scan.yaml
Labels: Libraries: Out of sync, not bug or enhancement

#928 [MISC] Sync up changes from 14
  .github/pull_request_template.md
  .github/workflows/tiobe_scan.yaml
  README.md
  SECURITY.md
  lib/charms/postgresql_k8s/v0/postgresql.py
  poetry.lock
  pyproject.toml
  src/backups.py
  templates/patroni.yml.j2
  tests/integration/test_backups_gcp.py
  tests/integration/test_config.py
  tests/unit/test_backups.py
Labels: Libraries: Out of sync, not bug or enhancement

#923 [DPE-6815] disable pgaudit during extensions changes
  lib/charms/data_platform_libs/v0/data_interfaces.py
  lib/charms/grafana_k8s/v0/grafana_dashboard.py
  lib/charms/postgresql_k8s/v0/postgresql.py
  lib/charms/prometheus_k8s/v0/prometheus_scrape.py
  tests/integration/test_plugins.py
  tests/unit/test_postgresql.py
Labels: bug, Libraries: Out of sync

#931 [DPE-6815] disable pgaudit during extensions change
  lib/charms/data_platform_libs/v0/data_interfaces.py
  lib/charms/grafana_k8s/v0/grafana_dashboard.py
  lib/charms/postgresql_k8s/v0/postgresql.py
  lib/charms/prometheus_k8s/v0/prometheus_scrape.py
  tests/unit/test_postgresql.py
Labels: Libraries: Out of sync, not bug or enhancement

#932 [DPE-6344] Remove CA transferred check
  src/charm.py
  src/ldap.py
  tests/unit/test_ldap.py
Labels: Libraries: Out of sync, not bug or enhancement

#943 [MISC] Sync main into 16/edge
  src/charm.py
  src/ldap.py
  src/relations/postgresql_provider.py
  tests/integration/ha_tests/test_upgrade.py
  tests/integration/ha_tests/test_upgrade_from_stable.py
  tests/integration/helpers.py
  tests/unit/test_ldap.py
  tests/unit/test_postgresql_provider.py
Labels: Libraries: Out of sync, not bug or enhancement

#934 [DPE-6664] Make username mandatory in set-password
  src/charm.py
  tests/unit/test_charm.py
Labels: enhancement, Libraries: Out of sync

#947 [MISC] Mandatory scope in promote action
  actions.yaml
Labels: enhancement, Libraries: Out of sync
