Repository canonical/postgresql-k8s-operator, pull requests merged in 2025-02, with the labels that each got.

#846 [DPE-6053] Fix ports
  lib/charms/data_platform_libs/v0/data_interfaces.py
  lib/charms/data_platform_libs/v0/data_models.py
  lib/charms/grafana_k8s/v0/grafana_dashboard.py
  lib/charms/observability_libs/v1/kubernetes_service_patch.py
  lib/charms/prometheus_k8s/v0/prometheus_scrape.py
  lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py
  lib/charms/tempo_coordinator_k8s/v0/tracing.py
  src/charm.py
  tests/integration/helpers.py
  tests/unit/test_async_replication.py
  tests/unit/test_backups.py
  tests/unit/test_charm.py
  tests/unit/test_db.py
  tests/unit/test_patroni.py
  tests/unit/test_postgresql.py
  tests/unit/test_postgresql_provider.py
  tests/unit/test_postgresql_tls.py
  tests/unit/test_upgrade.py
Labels: Libraries: OK

#842 [MISC] Define charm utility properties
  src/backups.py
  src/charm.py
  src/relations/async_replication.py
  src/relations/db.py
  src/relations/postgresql_provider.py
  tests/unit/test_charm.py
Labels: Libraries: Out of sync

#853 [MISC] Split topology script
  charmcraft.yaml
  scripts/__init__.py
  scripts/rotate_logs.py
  src/backups.py
  tests/unit/test_rotate_logs.py
  tox.ini
Labels: Libraries: Out of sync

#784 [DPE-5827] Set all nodes to synchronous replicas
  config.yaml
  src/charm.py
  src/config.py
  src/patroni.py
  src/upgrade.py
  templates/patroni.yml.j2
  tests/integration/ha_tests/helpers.py
  tests/integration/ha_tests/test_async_replication.py
  tests/integration/ha_tests/test_synchronous_policy.py
  tests/integration/helpers.py
  tests/integration/test_config.py
  tests/integration/test_tls.py
  tests/spread/test_synchronous_policy.py/task.yaml
  tests/unit/test_charm.py
  tests/unit/test_patroni.py
  tests/unit/test_upgrade.py
Labels: enhancement, Libraries: Out of sync

#850 [DPE-6484] Add scope to promote to primary
  actions.yaml
  src/charm.py
  src/patroni.py
  src/relations/async_replication.py
  tests/integration/ha_tests/test_async_replication.py
  tests/integration/test_charm.py
  tests/unit/test_async_replication.py
  tests/unit/test_charm.py
  tests/unit/test_patroni.py
Labels: enhancement, Libraries: Out of sync

#861 [MISC] Enable RBAC in tests
  concierge.yaml
  lib/charms/grafana_k8s/v0/grafana_dashboard.py
  lib/charms/prometheus_k8s/v0/prometheus_scrape.py
  lib/charms/rolling_ops/v0/rollingops.py
  lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py
  poetry.lock
  pyproject.toml
  tests/integration/relations/test_relations.py
  tests/integration/test_trust.py
Labels: Libraries: OK, not bug or enhancement

#862 [MISC] Define charm constants
  lib/charms/postgresql_k8s/v0/postgresql.py
  src/charm.py
  src/constants.py
  tests/integration/helpers.py
  tests/integration/new_relations/test_new_relations_1.py
  tests/integration/new_relations/test_relations_coherence.py
  tests/unit/test_postgresql.py
Labels: Libraries: Out of sync, not bug or enhancement

#866 [DPE-6323] Handle missing stanza output
  src/backups.py
  tests/unit/test_backups.py
Labels: bug, Libraries: OK

#872 [MISC] Disable storage test on arm
  lib/charms/loki_k8s/v1/loki_push_api.py
  lib/charms/tempo_coordinator_k8s/v0/tracing.py
  tests/integration/test_storage.py
Labels: Libraries: OK, not bug or enhancement

#874 [MISC] Add degraded status to primary message
  src/charm.py
  src/patroni.py
  tests/unit/test_charm.py
  tests/unit/test_patroni.py
Labels: enhancement, Libraries: OK
