Repository canonical/postgresql-k8s-operator, pull requests merged in 2025-05, with the labels that each got.

#953 [DPE-6344] Persist transferred certificates upon start
  lib/charms/postgresql_k8s/v0/postgresql_tls.py
  src/charm.py
Labels: bug, Libraries: Out of sync

#941 [DPE-6964] Storage pools
  lib/charms/postgresql_k8s/v0/postgresql.py
  metadata.yaml
  poetry.lock
  src/charm.py
  src/relations/async_replication.py
  templates/patroni.yml.j2
  tests/helpers.py
  tests/integration/ha_tests/clean-data-dir.sh
  tests/integration/ha_tests/helpers.py
  tests/integration/ha_tests/test_smoke.py
  tests/integration/ha_tests/test_upgrade.py
  tests/integration/ha_tests/test_upgrade_from_stable.py
  tests/integration/helpers.py
  tests/integration/test_password_rotation.py
  tests/integration/test_storage.py
  tests/unit/test_charm.py
Labels: enhancement, Libraries: Out of sync

#957 [MISC] Extend relation-user listing syntax
  lib/charms/postgresql_k8s/v0/postgresql.py
  tests/unit/test_postgresql.py
Labels: bug, Libraries: Out of sync

#958 [MISC] Sync main to 16/edge
  lib/charms/postgresql_k8s/v0/postgresql.py
  lib/charms/postgresql_k8s/v0/postgresql_tls.py
  src/charm.py
  tests/unit/test_postgresql.py
Labels: Libraries: Out of sync, not bug or enhancement

#969 [MISC] Try to fix release
  .github/workflows/release.yaml
Labels: Libraries: Out of sync, not bug or enhancement

#919 [DPE-6899] User->databases pg_hba rules
  lib/charms/postgresql_k8s/v0/postgresql.py
  poetry.lock
  scripts/authorisation_rules_observer.py
  src/authorisation_rules_observer.py
  src/charm.py
  src/patroni.py
  src/relations/db.py
  src/relations/postgresql_provider.py
  src/upgrade.py
  templates/patroni.yml.j2
  tests/integration/helpers.py
  tests/integration/new_relations/test_new_relations_1.py
  tests/integration/test_audit.py
  tests/integration/test_pg_hba.py
  tests/spread/test_pg_hba.py/task.yaml
  tests/unit/test_charm.py
  tests/unit/test_db.py
  tests/unit/test_postgresql.py
  tests/unit/test_postgresql_provider.py
Labels: enhancement, Libraries: Out of sync

#971 [MISC] Sync main to 16/edge and update libs
  lib/charms/data_platform_libs/v0/data_interfaces.py
  lib/charms/loki_k8s/v1/loki_push_api.py
  lib/charms/postgresql_k8s/v0/postgresql.py
  lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py
  lib/charms/tempo_coordinator_k8s/v0/tracing.py
  lib/charms/tls_certificates_interface/v2/tls_certificates.py
  scripts/authorisation_rules_observer.py
  src/authorisation_rules_observer.py
  src/charm.py
  src/patroni.py
  src/relations/postgresql_provider.py
  src/upgrade.py
  templates/patroni.yml.j2
  tests/integration/helpers.py
  tests/integration/new_relations/test_new_relations_1.py
  tests/integration/test_audit.py
  tests/integration/test_pg_hba.py
  tests/spread/test_pg_hba.py/task.yaml
  tests/unit/test_charm.py
  tests/unit/test_postgresql.py
  tests/unit/test_postgresql_provider.py
Labels: Libraries: Out of sync, not bug or enhancement
